name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - "starter/backend/**"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t backend:${{ github.sha }} .
          docker tag backend:${{ github.sha }} 868825397679.dkr.ecr.us-east-1.amazonaws.com/backend:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push 868825397679.dkr.ecr.us-east-1.amazonaws.com/backend:${{ github.sha }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig --name cluster --region us-east-1

      - name: Deploy backend
        working-directory: starter/backend/k8s
        run: |
          kustomize edit set image backend=868825397679.dkr.ecr.us-east-1.amazonaws.com/backend:${{ github.sha }}
          kustomize build | kubectl apply -f -