name: Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "starter/frontend/**"

  workflow_dispatch:

jobs:
  **nt:
    runs-on: ubuntu-latest

 ** defaults:
      run:
        wor**ng-directory: starter/frontend

 ** steps:
      - uses: actions/che**out@v4

      - uses: actions/set**-node@v4
        with:
          **de-version: 18

      - run: npm **stall

      - run: npm run lint
** test:
    runs-on: ubuntu-latest**    defaults:
      run:
        **rking-directory: starter/frontend**    steps:
      - uses: actions/**eckout@v4

      - uses: actions/**tup-node@v4
        with:
       ** node-version: 18

      - run: n** install

      - run: CI=true np**test

  build:
    needs:
      -**int
      - test

    runs-on: ub**tu-latest

    steps:
      - use** actions/checkout@v4

      - nam** Build Docker image
        run: **          docker build \
        **  -t frontend:${{ github.sha }} \**
           starter/frontend